typography_spectrum: 0.057768292957916856
color:
  brandColors:
    - '#726277'
    - '#808080'
    - '#000000'
    - '#804080'
    - '#ffffff'
  brandStrength: 0.3360998041462153
  lightness: 0.7201699381694198
  saturation: 0.740739461267367
  rhythmicContrast: 0.7027318531181663
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.08052807697094977
analytics:
  google: null
  facebook: null
  twitter: null
name: Chiang Mai Adventures
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: Your Next Adventure Starts Here
purpose: []
